base_model: "jeffmeloy/Qwen2.5-7B-nerd-uncensored-v1.2"
fine_tuned_models: # uncomment the models you want to merge
##### Qwen2.5 7B Models #####
#- "Qwen/Qwen2.5-7B"
#- "Qwen/Qwen2.5-7B-Instruct"
#- "EVA-UNIT-01/EVA-Qwen2.5-7B-v0.1"
#- "FourOhFour/Vapor_v2_7B"
#- "Goekdeniz-Guelmez/Josiefied-Qwen2.5-7B-Instruct-abliterated-v2"
#- "happzy2633/qwen2.5-7b-ins-v3"
#- "huihui-ai/Qwen2.5-7B-Instruct-abliterated-v2"
#- "HumanLLMs/Humanish-Qwen2.5-7B-Instruct"
#- "Orion-zhen/Qwen2.5-7B-Instruct-Uncensored"
#- "Orion-zhen/Meissa-Qwen2.5-7B-Instruct"
#- "sethuiyer/Qwen2.5-7B-Anvita"
#- "rombodawg/Rombos-LLM-V2.5-Qwen-7b"
#- "Cran-May/T.E-8.1"
#- "beomi/Qwen2.5-7B-Instruct-kowiki-qa"
#- "Orion-zhen/Qwen2.5-7B-Gutenberg-KTO"
#- "fblgit/cybertron-v4-qw7B-MGS"
#- "nguyentd/FinancialAdvice-Qwen2.5-7B"
#- "WhiteRabbitNeo/WhiteRabbitNeo-2.5-Qwen-2.5-Coder-7B"
#- "edgerunner-ai/EdgeRunner-Command-Nested"
#- "katanemo/Arch-Function-7B"
#- "DeepGlint-AI/llava-mlcd-qwen2.5-7b"
- "jeffmeloy/Qwen2.5-7B-nerd-uncensored-v0.9"
- "jeffmeloy/Qwen2.5-7B-nerd-uncensored-v1.0"
- "jeffmeloy/Qwen2.5-7B-nerd-uncensored-v1.1"
- "jeffmeloy/Qwen2.5-7B-nerd-uncensored-v1.2"
- "jeffmeloy/Qwen2.5-7B-nerd-uncensored-v1.3"
- "composite_model_20241105_010655_final_stabalized"
- "composite_model_20241105_075024_final_stabalized"
- "composite_model_20241105_081533_final_stabalized"
- "composite_model_20241105_160424_final_stabalized"
##- "AmberYifan/Qwen2.5-7B-dpo-2k"
##- "mergekit-community/mergekit-slerp-aflqaqy"
##- "mergekit-community/mergekit-ties-inxwsfo"
##- "Qwen/Qwen2.5-Coder-7B-Instruct"
##- "Qwen/Qwen2.5-Math-7B-Instruct" 
##- "Qwen/Qwen2.5-Coder-7B"
##- "Qwen/Qwen2.5-Math-7B"
##- "thomas-yanxin/XinYuan-Qwen2.5-7B-0917"
##- "jbjeong91/Qwen2.5_7B_IST_StoryGen_vanilla"
##- "AmberYifan/Qwen2.5-7B-dpo-2k-hhrlhf"
##- "jbjeong91/Qwen2.5_7B_IST_StoryGen_test2" 
##- "OpenBuddy/openbuddy-qwen2.5llamaify-7b-v23.1-200k"
##- "BenevolenceMessiah/Qwen2.5-Coder-7B-3x-Instruct-TIES-v1.1"
##- "MadeAgents/Hammer2.0-7b"
##- "Etherll/Qwen2.5-Coder-7B-Instruct-Ties"
##### Mistral 7B Models #####
#- "senseable/WestLake-7B-v2"
#- "BarraHome/Mistroll-7B-v2.2"
#- "MaziyarPanahi/Calme-7B-Instruct-v0.2"
#- "chihoonlee10/T3Q-Mistral-UB-DPO-v1.0"
#- "jeffmeloy/mistral-nerd-7B-v1"
#- "bobofrut/ladybird-base-7B-v8"
#- "flammenai/flammen18X-mistral-7B"
#- "S-miguel/The-Trinity-Coder-7B"
models_dir: "E:/input_models/"
output_dir: "E:/merged_model/"
metric_dir: "./metrics/"
ties_enabled: true